services:
  annotation-fluent-api:
    build: 
      context: .
      dockerfile: Annotations/DOCKERFILE
    container_name: annotation-fluent-api
    volumes:
      - ./Annotations/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db:
        condition: service_healthy

  fluent-api-fluent-api:
    build: 
      context: .
      dockerfile: "Fluent API/DOCKERFILE"
    container_name: fluent-api-fluent-api
    volumes:
      - ./Fluent API/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db:
        condition: service_healthy

  inheritance-table-per-class:
    build: 
      context: .
      dockerfile: InheritanceTablePerClass/DOCKERFILE
    container_name: inheritance-table-per-class-fluent-api
    volumes:
      - ./InheritanceTablePerClass/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db:
        condition: service_healthy

  inheritance-table-per-hierarchy:
    build: 
      context: .
      dockerfile: InheritanceTablePerHierarchy/DOCKERFILE
    container_name: inheritance-table-per-hierarchy-fluent-api
    volumes:
      - ./InheritanceTablePerHierarchy/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db:
        condition: service_healthy

  inheritance-table-per-type:
    build: 
      context: .
      dockerfile: InheritanceTablePerType/DOCKERFILE
    container_name: inheritance-table-per-type-fluent-api
    volumes:
      - ./InheritanceTablePerType/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db:
        condition: service_healthy

  many-to-many:
    build: 
      context: .
      dockerfile: Many-to-many/DOCKERFILE
    container_name: many-to-many-fluent-api
    volumes:
      - ./Many-to-many/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db:
        condition: service_healthy


  one-to-many:
    build: 
      context: .
      dockerfile: One-to-Many/DOCKERFILE
    container_name: one-to-many-fluent-api
    volumes:
      - ./One-to-Many/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER_FILE=/run/secrets/psql_user
      - POSTGRES_DB_FILE=/run/secrets/psql_dbname
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_pass

    secrets:
      - psql_user
      - psql_dbname
      - psql_pass

    ports:
      - "5432:5432"
    networks:
      - my-bd-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ellina -d postgres"]
      interval: 10s      
      timeout: 5s
      retries: 5
      start_period: 10s
    
    
networks:
  my-bd-network:
    driver: bridge

volumes:
  postgres_data:

secrets:
  psql_user:
    file: ./secrets/psql_user.txt
  psql_dbname:
    file: ./secrets/psql_dbname.txt
  psql_pass:
    file: ./secrets/psql_pass.txt
 