FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /dotnet
COPY ["Fluent API.sln", "./"]
COPY 'Fluent Api'/'Fluent Api.csproj' 'Fluent Api'/
RUN dotnet restore 'Fluent Api'/'Fluent Api.csproj'


COPY . .
WORKDIR /dotnet/'Fluent Api'
RUN dotnet publish 'Fluent Api.csproj' -c Release -o /app/publish /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine AS release
WORKDIR /app
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
COPY --from=build /app/publish .

CMD ["dotnet", "Fluent Api.dll"]
