FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /dotnet
COPY ["Fluent API.sln", "./"]
COPY ["Fluent API/Fluent API.csproj", "Fluent API/"]
RUN dotnet restore "Fluent API/Fluent API.csproj"

COPY . .
WORKDIR "/dotnet/Fluent API"
RUN dotnet publish "Fluent API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine AS release
WORKDIR /app
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
COPY --from=build /app/publish .

CMD ["dotnet", "Fluent API.dll"]