

services:

  annotation-fluent-api:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: annotation-fluent-api
    volumes:
      - ./Annotations/appsettings.json:/app/appsettings.json:ro
    networks:
      - my-bd-network
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    
    environment:
      POSTGRES_DB: Students_postgres
      POSTGRES_USER: ellina
      POSTGRES_PASSWORD: secret_lesson_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-bd-network

      
    
    
networks:
  my-bd-network:
    driver: bridge

volumes:
  postgres_data:
    driver: volume