FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /dotnet
COPY ["Fluent API.sln", "./"]
COPY InheritanceTablePerHierarchy/InheritanceTablePerHierarchy.csproj InheritanceTablePerHierarchy/
RUN dotnet restore InheritanceTablePerHierarchy/InheritanceTablePerHierarchy.csproj


COPY . .
WORKDIR /dotnet/InheritanceTablePerHierarchy
RUN dotnet publish InheritanceTablePerHierarchy.csproj -c Release -o /app/publish /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine AS release
WORKDIR /app
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
COPY --from=build /app/publish .
RUN apk add --no-cache icu-libs

CMD ["dotnet", "InheritanceTablePerHierarchy.dll"]
