FROM mcr.microsoft.com/dotnet/sdk:7.0-alpine AS build
WORKDIR /dotnet
COPY ["Fluent API.sln", "./"]
COPY One-to-Many/One-to-Many.csproj One-to-Many/
RUN dotnet restore One-to-Many/One-to-Many.csproj


COPY . .
WORKDIR /dotnet/One-to-Many
RUN dotnet publish One-to-Many.csproj -c Release -o /app/publish /p:UseAppHost=false


FROM mcr.microsoft.com/dotnet/runtime:7.0-alpine AS release
WORKDIR /app
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
COPY --from=build /app/publish .
RUN apk add --no-cache icu-libs

CMD ["dotnet", "One-to-Many.dll"]
